vars:
  - params.yaml

stages:
  wget:
    cmd: >
      ${docker_cmd} ${wget.img}
      ${wget.data_url} ${docker_out_dir}/${wget.out_dir}
    outs:
    - ${out_dir}/${wget.out_dir}

  untar:
    cmd: >
      ${docker_cmd} ${untar.img}
      ${untar.tar_args}  ${docker_out_dir}/${untar.data_dir}  ${docker_out_dir}/${wget.out_dir}
      ${untar.tar_file_name}
    deps:
    - ${out_dir}/${wget.out_dir}
    outs:
    - ${out_dir}/${untar.data_dir}

  clean:
    cmd: >
      ${docker_cmd} ${clean.img}
      --data_dir ${docker_out_dir}/${untar.data_dir}
      --cleaned_dir_name ${docker_out_dir}/${clean.out_dir}
    deps:
    - ${out_dir}/${untar.data_dir}
    outs:
    - ${out_dir}/${clean.out_dir}

  split:
    cmd: >
      ${docker_cmd} ${split.img}
      --data-dir ${docker_out_dir}/${combine.out_dir}
      --train-dir ${docker_out_dir}/${split.train_dir}
      --test-dir ${docker_out_dir}/${split.test_dir}
      --ratio ${split.ratio}
      --by-label False
    deps:
    - ${out_dir}/${combine.out_dir}
    params:
    - split.ratio
    outs:
    - ${out_dir}/${split.train_dir}
    - ${out_dir}/${split.test_dir}
    
  siamese:
    foreach: ${siamese_types}
    do:
      cmd: >
        python ${siamese_src}
        --train_dir ${out_dir}/${split.train_dir}
        --test_dir ${out_dir}/${split.test_dir}
        --distance ${item.distance}
        --out_model_path ${item.out_model_path}
        --out_encoder_path ${item.out_encoder_path}
        --out_metrics_path ${item.out_metrics_path}
        --out_summaries_path ${item.out_summaries_path}
        --mutate_anchor ${siamese.mutate_anchor}
        --mutate_other ${siamese.mutate_other}
        --dense_reg_rate ${siamese.dense_reg_rate}
        --conv_reg_rate ${siamese.conv_reg_rate}
        --latent_nodes ${siamese.latent_nodes}
        --final_activation ${siamese.final_activation}
        --lr ${siamese.lr}
        --optimizer ${siamese.optimizer}
        --epochs ${siamese.epochs}
        --batch_size ${siamese.batch_size}
        --reduce_lr_factor ${siamese.reduce_lr_factor}
        --reduce_lr_patience ${siamese.reduce_lr_patience}
        --use_batch_norm ${siamese.use_batch_norm}
        --use_sigmoid ${siamese.use_sigmoid}
        --monitor_metric ${siamese.monitor_metric}
        --pooling ${siamese.pooling}
        --conv_layers ${siamese.conv_layers}
    
      params:
        - siamese
      deps:
        #- gloves/imagenet.py
        - ${siamese_model_src}
        - ${out_dir}/${split.train_dir}
        - ${out_dir}/${split.test_dir}
      outs:
        - ${item.out_model_path}
        - ${item.out_encoder_path}
      # TODO why no metrics html?
      #plots:
        #- ${item.out_metrics_path}
      metrics:
        #- ${item.out_metrics_path}.html
        - ${item.out_metrics_path}.json:
            cache: false
        - ${item.out_summaries_path}
  # siamese_main:
  #   cmd: >
  #     python ${siamese_src}
  #     --train_dir ${out_dir}/${split.train_dir}
  #     --test_dir ${out_dir}/${split.test_dir}
  #     --distance ${siamese.distance}
  #     --out_model_path ${siamese.out_model_path}
  #     --out_encoder_path ${siamese.out_encoder_path}
  #     --out_metrics_path ${siamese.out_metrics_path}
  #     --out_summaries_path ${siamese.out_summaries_path}
  #     --mutate_anchor ${siamese.mutate_anchor}
  #     --mutate_other ${siamese.mutate_other}
  #     --dense_reg_rate ${siamese.dense_reg_rate}
  #     --conv_reg_rate ${siamese.conv_reg_rate}
  #     --latent_nodes ${siamese.latent_nodes}
  #     --final_activation ${siamese.final_activation}
  #     --lr ${siamese.lr}
  #     --optimizer ${siamese.optimizer}
  #     --epochs ${siamese.epochs}
  #     --batch_size ${siamese.batch_size}
  #     --reduce_lr_factor ${siamese.reduce_lr_factor}
  #     --reduce_lr_patience ${siamese.reduce_lr_patience}
  #     --use_batch_norm ${siamese.use_batch_norm}
  #     --use_sigmoid ${siamese.use_sigmoid}
  #     --monitor_metric ${siamese.monitor_metric}
    
  #   params:
  #     - siamese
  #   deps:
  #     - ${siamese_src}
  #     - ${siamese_model_src}
  #     - ${out_dir}/${split.train_dir}
  #     - ${out_dir}/${split.test_dir}
  #   outs:
  #     - ${siamese.out_model_path}
  #     - ${siamese.out_encoder_path}
  #   # TODO why no metrics html?
  #   plots:
  #     - ${siamese.out_metrics_path}
  #   metrics:
  #     #- ${item.out_metrics_path}.html
  #     - ${siamese.out_metrics_path}.json:
  #         cache: false
  #     - ${siamese.out_summaries_path}


  # siamese:
  #   foreach: ${siamese_types}
  #   do:
  #     cmd: >
  #       python ${siamese_src}
  #       --train-dir ${out_dir}/${split.train_dir}
  #       --test-dir ${out_dir}/${split.test_dir}
  #       --distance ${item.distance}
  #       --out-model-path ${item.out_model_path}
  #       --out-encoder-path ${item.out_encoder_path}
  #       --out-metrics-path ${item.out_metrics_path}
  #       --out-summaries-path ${item.out_summaries_path}
     
  #     params:
  #       - siamese
  #     deps:
  #       - ${siamese_src}
  #       - ${siamese_model_src}
  #       - ${out_dir}/${split.train_dir}
  #       - ${out_dir}/${split.test_dir}
  #     outs:
  #       - ${item.out_model_path}
  #       - ${item.out_encoder_path}
  #     # TODO why no metrics html?
  #     plots:
  #       - ${item.out_metrics_path}
  #     metrics:
  #       #- ${item.out_metrics_path}.html
  #       - ${item.out_metrics_path}.json:
  #           cache: false
  #       - ${item.out_summaries_path}

  # classifier:
  #   foreach: ${classifier_types}
  #   do:
  #     cmd: >
  #       python ${classifier_src}
  #       --encoder-model-path ${siamese_types.l2_distance.out_encoder_path}
  #       --train-dir ${out_dir}/${split.train_dir}
  #       --test-dir ${out_dir}/${split.test_dir}
  #       --param-path params.yaml
  #       --param-parent-key classifier
  #       --out-model-path ${item.out_model_path}
  #       --out-label-encoder-path ${item.out_label_encoder}
  #       --out-metrics-path ${item.out_metrics_path}
  #       --mixed-precision ${siamese.mixed_precision}
  #       --use-imagenet ${item.use_imagenet}
  #       --is-frozen ${item.is_frozen}
  #     params:
  #       - classifier
  #     deps:
  #       - ${classifier_src}
  #       - ${siamese_types.l2_distance.out_encoder_path}
  #       - ${out_dir}/${split.train_dir}
  #       - ${out_dir}/${split.test_dir}
  #       - ${item.model_src}
  #     outs:
  #       - ${item.out_model_path}
  #       - ${item.out_label_encoder}
  #     # TODO why no metrics html?
  #     plots:
  #       - ${item.out_metrics_path}
  #     metrics:
  #       - ${item.out_metrics_path}.json:
  #           cache: false
  #       #- ${item.out_summaries_path}
  #     #live:
  #       #${item.out_metrics_path}:
  #         #summary: true
  #         #html: true

  # TODO continue hydra experiments
  #hydra:
    #cmd: >
      #${docker_cmd} ${train.docker_args} 
      #${train.img} hydra.py
    #params:
      #- train.img
      #- train.docker_args
    #deps:
      #- last_build.log
      
  get_my_pets:
    cmd: >
      ${docker_cmd}
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      amazon/aws-cli:2.4.10
      --endpoint-url $S3_ENDPOINT s3 cp ${get_my_pets.bucket} ${docker_out_dir}/${get_my_pets.out_dir} --recursive
    outs:
    - ${out_dir}/${get_my_pets.out_dir}

  rename_my_pets:
    cmd: >
      ${docker_cmd}
      bash:5.1.16-alpine3.14
      bash
      ${docker_work_dir}/scripts/rename.sh  
      ${docker_out_dir}/${get_my_pets.out_dir} 
      ${docker_out_dir}/${rename_my_pets.out_dir}
    deps:
      - scripts/rename.sh
      - ${out_dir}/${get_my_pets.out_dir}
    outs:
    - ${out_dir}/${rename_my_pets.out_dir}


  combine:
    cmd: >
      ${docker_cmd} alpine:3.15.0
      sh -c 'mkdir -p ${docker_out_dir}/${combine.out_dir} && cp -r ${docker_out_dir}/${rename_my_pets.out_dir}/* ${docker_out_dir}/${clean.out_dir}/* ${docker_out_dir}/${combine.out_dir}'
    deps:
    - ${out_dir}/${rename_my_pets.out_dir}
    - ${out_dir}/${clean.out_dir}
    outs:
    - ${out_dir}/${combine.out_dir}
  