vars:
  - params.yaml

stages:
  wget:
    cmd: >
      ${docker_cmd} ${wget.img}
      ${wget.data_url} ${docker_out_dir}/${wget.out_dir}
    outs:
    - ${out_dir}/${wget.out_dir}

  untar:
    cmd: >
      ${docker_cmd} ${untar.img}
      ${untar.tar_args}  ${docker_out_dir}/${untar.data_dir}  ${docker_out_dir}/${wget.out_dir}
      ${untar.tar_file_name}
    deps:
    - ${out_dir}/${wget.out_dir}
    outs:
    - ${out_dir}/${untar.data_dir}

  clean:
    cmd: >
      ${docker_cmd} ${clean.img}
      --data_dir ${docker_out_dir}/${untar.data_dir}
      --cleaned_dir_name ${docker_out_dir}/${clean.out_dir}
    deps:
    - ${out_dir}/${untar.data_dir}
    outs:
    - ${out_dir}/${clean.out_dir}

  split:
    cmd: >
      ${docker_cmd} ${split.img}
      --data-dir ${docker_out_dir}/${combine.out_dir}
      --train-dir ${docker_out_dir}/${split.train_dir}
      --test-dir ${docker_out_dir}/${split.test_dir}
      --ratio ${split.ratio}
      --by-label False
    deps:
    - ${out_dir}/${combine.out_dir}
    params:
    - split.ratio
    outs:
    - ${out_dir}/${split.train_dir}
    - ${out_dir}/${split.test_dir}
    
  # siamese_pretrain:
  #   foreach: ${siamese_types}
  #   do:
  #     cmd: >
  #       python gloves/main.py
  #       --train-dir /nfs/data/imagenet/imagenet21k_resized/imagenet21k_train
  #       --test-dir  /nfs/data/imagenet/imagenet21k_resized/imagenet21k_train
  #       --sigmoid-head ${item.sigmoid_head}
  #       --param-path params.yaml
  #       --param-parent-key siamese
  #       --out-model-path ${item.out_model_path}_imagenet
  #       --out-encoder-path ${item.out_encoder_path}_imagenet
  #       --out-metrics-path ${item.out_metrics_path}_imagenet
  #       --out-summaries-path ${item.out_summaries_path}_imagenet
  #       --glob-pattern "**/*.JPEG"
  #       --nway-disabled True
  #       --label-func path
  #     params:
  #       - siamese
  #     deps:
  #       - gloves/imagenet.py
  #       - ${siamese_model_src}
  #       #- ${out_dir}/${split.train_dir}_imagenet
  #       #- ${out_dir}/${split.test_dir}_imagenet
  #     outs:
  #       - ${item.out_model_path}_imagenet
  #       - ${item.out_encoder_path}_imagenet
  #     # TODO why no metrics html?
  #     #plots:
  #       #- ${item.out_metrics_path}_imagenet
  #     #metrics:
  #       #- ${item.out_metrics_path}.html
  #       #- ${item.out_metrics_path}_imagenet.json:
  #           #cache: false
  #       #- ${item.out_summaries_path}_imagenet

  siamese:
    foreach: ${siamese_types}
    do:
      cmd: >
        python ${siamese_src}
        --train-dir ${out_dir}/${split.train_dir}
        --test-dir ${out_dir}/${split.test_dir}
        --loss ${item.loss}
        --param-path params.yaml
        --param-parent-key siamese
        --out-model-path ${item.out_model_path}
        --out-encoder-path ${item.out_encoder_path}
        --out-metrics-path ${item.out_metrics_path}
        --out-summaries-path ${item.out_summaries_path}
     
      params:
        - siamese
      deps:
        - ${siamese_src}
        - ${siamese_model_src}
        - ${out_dir}/${split.train_dir}
        - ${out_dir}/${split.test_dir}
      outs:
        - ${item.out_model_path}
        - ${item.out_encoder_path}
      # TODO why no metrics html?
      plots:
        - ${item.out_metrics_path}
      metrics:
        #- ${item.out_metrics_path}.html
        - ${item.out_metrics_path}.json:
            cache: false
        - ${item.out_summaries_path}

  classifier:
    foreach: ${classifier_types}
    do:
      cmd: >
        python ${classifier_src}
        --encoder-model-path ${siamese_types.l2_distance.out_encoder_path}
        --train-dir ${out_dir}/${split.train_dir}
        --test-dir ${out_dir}/${split.test_dir}
        --param-path params.yaml
        --param-parent-key classifier
        --out-model-path ${item.out_model_path}
        --out-label-encoder-path ${item.out_label_encoder}
        --out-metrics-path ${item.out_metrics_path}
        --mixed-precision ${siamese.mixed_precision}
        --use-imagenet ${item.use_imagenet}
        --is-frozen ${item.is_frozen}
      params:
        - classifier
      deps:
        - ${classifier_src}
        - ${siamese_types.l2_distance.out_encoder_path}
        - ${out_dir}/${split.train_dir}
        - ${out_dir}/${split.test_dir}
      outs:
        - ${item.out_model_path}
        - ${item.out_label_encoder}
      # TODO why no metrics html?
      plots:
        - ${item.out_metrics_path}
      metrics:
        - ${item.out_metrics_path}.json:
            cache: false
        #- ${item.out_summaries_path}
      #live:
        #${item.out_metrics_path}:
          #summary: true
          #html: true

  # TODO continue hydra experiments
  #hydra:
    #cmd: >
      #${docker_cmd} ${train.docker_args} 
      #${train.img} hydra.py
    #params:
      #- train.img
      #- train.docker_args
    #deps:
      #- last_build.log
      
  get_my_pets:
    cmd: >
      ${docker_cmd}
      -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      amazon/aws-cli:2.4.10
      --endpoint-url $S3_ENDPOINT s3 cp ${get_my_pets.bucket} ${docker_out_dir}/${get_my_pets.out_dir} --recursive
    outs:
    - ${out_dir}/${get_my_pets.out_dir}

  rename_my_pets:
    cmd: >
      ${docker_cmd}
      bash:5.1.16-alpine3.14
      bash
      ${docker_work_dir}/scripts/rename.sh  
      ${docker_out_dir}/${get_my_pets.out_dir} 
      ${docker_out_dir}/${rename_my_pets.out_dir}
    deps:
      - scripts/rename.sh
      - ${out_dir}/${get_my_pets.out_dir}
    outs:
    - ${out_dir}/${rename_my_pets.out_dir}


  combine:
    cmd: >
      ${docker_cmd} alpine:3.15.0
      sh -c 'mkdir -p ${docker_out_dir}/${combine.out_dir} && cp -r ${docker_out_dir}/${rename_my_pets.out_dir}/* ${docker_out_dir}/${clean.out_dir}/* ${docker_out_dir}/${combine.out_dir}'
    deps:
    - ${out_dir}/${rename_my_pets.out_dir}
    - ${out_dir}/${clean.out_dir}
    outs:
    - ${out_dir}/${combine.out_dir}
  