vars:
- params.yaml
  # TODO figure out how to paramaterize outputs here
  #- docker_cmd: docker run -v $(pwd)/outputs:/outputs
- aws_cp: aws s3 --endpoint-url https://minio.etheredge.co cp

stages:
  wget:
    cmd: >
      ${docker_cmd} ${wget.img}
      ${wget.data_url} ${docker_out_dir}/${wget.out_dir}
    params:
    - wget
    outs:
    - ${out_dir}/${wget.out_dir}

  #move_wget:
    #cmd: ${aws_cp} ${out_dir}/${wget.out_dir} s3://gloves/${wget.out_dir}
    #deps:
      #- ${out_dir}/${wget.out_dir}
    #outs:
      #- s3://gloves/${wget.out_dir}

  untar:
    cmd: >
      ${docker_cmd} ${untar.img}
      ${untar.tar_args}  ${docker_out_dir}/${untar.data_dir}  ${docker_out_dir}/${wget.out_dir}
      ${untar.tar_file_name}
    deps:
    - ${out_dir}/${wget.out_dir}
    params:
    - untar
    - wget.out_dir
    outs:
    - ${out_dir}/${untar.data_dir}

  clean:
    cmd: >
      ${docker_cmd} ${clean.img}
      --data_dir ${docker_out_dir}/${untar.data_dir}
      --cleaned_dir_name ${docker_out_dir}/${clean.out_dir}
    deps:
    - ${out_dir}/${untar.data_dir}
    params:
    - clean
    - untar.data_dir
    outs:
    - ${out_dir}/${clean.out_dir}

  split:
    cmd: >
      ${docker_cmd} ${split.img}
      --data-dir ${docker_out_dir}/${clean.out_dir}
      --train-dir ${docker_out_dir}/${split.train_dir}
      --test-dir ${docker_out_dir}/${split.test_dir}
      --ratio ${split.ratio}
      --by-label False
    deps:
    - ${out_dir}/${clean.out_dir}
    params:
    - out_dir
    - split
    - clean.out_dir
    outs:
    - ${out_dir}/${split.train_dir}
    - ${out_dir}/${split.test_dir}

  build_image:
    cmd: ./build_image.sh && echo $(date) > last_build.log
    deps:
      - Dockerfile
      - build_image.sh
      - requirements.txt
      - gloves/
    outs:
      - last_build.log
    
  train_siamese:
    cmd: >
      ${docker_cmd} ${train.docker_args} ${train.img} 
      main.py
      --train-dir ${docker_out_dir}/${split.train_dir}
      --test-dir ${docker_out_dir}/${split.test_dir}
      --model-dir ${docker_out_dir}/${train.model_dir}
      --model-filename ${train.model_filename}
      --encoder-model ${docker_out_dir}/${train.encoder}
    params:
      - out_dir
      - train
      - split.train_dir
      - split.test_dir
    deps:
      - last_build.log
      - ${out_dir}/${split.train_dir}
      - ${out_dir}/${split.test_dir}
    outs:
      - ${out_dir}/${train.model_dir}/${train.model_filename}
      - ${out_dir}/${train.encoder}


  classifier:
    cmd: >
      ${docker_cmd} ${train.docker_args} 
      ${train.img} classifier.py
      --encoder-model-path ${docker_out_dir}/${train.encoder}
      --train-dir ${docker_out_dir}/${split.train_dir}
      --test-dir ${docker_out_dir}/${split.test_dir}
      --model-path ${docker_out_dir}/${classifier.model_dir}
      --label-encoder-path ${docker_out_dir}/${classifier.label_encoder}
    params:
      - classifier
      - train.img
      - train.docker_args
      - train.encoder
      - split.train_dir
    deps:
      - last_build.log
      - ${out_dir}/${train.encoder}
      - ${out_dir}/${split.train_dir}
      - ${out_dir}/${split.test_dir}
    outs:
      - ${out_dir}/${classifier.model_dir}

