vars:
  - params.yaml

stages:
  wget:
    cmd: >
      ${docker_cmd} ${wget.img}
      ${wget.data_url} ${docker_out_dir}/${wget.out_dir}
    outs:
    - ${out_dir}/${wget.out_dir}

  untar:
    cmd: >
      ${docker_cmd} ${untar.img}
      ${untar.tar_args}  ${docker_out_dir}/${untar.data_dir}  ${docker_out_dir}/${wget.out_dir}
      ${untar.tar_file_name}
    deps:
    - ${out_dir}/${wget.out_dir}
    outs:
    - ${out_dir}/${untar.data_dir}

  clean:
    cmd: >
      ${docker_cmd} ${clean.img}
      --data_dir ${docker_out_dir}/${untar.data_dir}
      --cleaned_dir_name ${docker_out_dir}/${clean.out_dir}
    deps:
    - ${out_dir}/${untar.data_dir}
    outs:
    - ${out_dir}/${clean.out_dir}

  split:
    cmd: >
      ${docker_cmd} ${split.img}
      --data-dir ${docker_out_dir}/${clean.out_dir}
      --train-dir ${docker_out_dir}/${split.train_dir}
      --test-dir ${docker_out_dir}/${split.test_dir}
      --ratio ${split.ratio}
      --by-label False
    deps:
    - ${out_dir}/${clean.out_dir}
    params:
    - split.ratio
    outs:
    - ${out_dir}/${split.train_dir}
    - ${out_dir}/${split.test_dir}
    
  siamese:
    foreach: ${siamese_types}
    do:
      cmd: >
        python ${siamese_src}
        --train-dir ${out_dir}/${split.train_dir}
        --test-dir ${out_dir}/${split.test_dir}
        --sigmoid-head ${item.sigmoid_head}
        --param-path params.yaml
        --param-parent-key siamese
        --out-model-path ${item.out_model_path}
        --out-encoder-path ${item.out_encoder_path}
        --out-metrics-path ${item.out_metrics_path}
        --out-summaries-path ${item.out_summaries_path}
      params:
        - siamese
      deps:
        - ${siamese_src}
        - ${out_dir}/${split.train_dir}
        - ${out_dir}/${split.test_dir}
      outs:
        - ${item.out_model_path}
        - ${item.out_encoder_path}
      # TODO why no metrics html?
      plots:
        - ${item.out_metrics_path}
      metrics:
        #- ${item.out_metrics_path}.html
        - ${item.out_metrics_path}.json:
            cache: false
        - ${item.out_summaries_path}

  classifiers:
    foreach: ${classifier_types}
    do:
      cmd: >
        python ${classifier_src}
        --encoder-model-path ${siamese_types.distance.out_encoder_path}
        --train-dir ${out_dir}/${split.train_dir}
        --test-dir ${out_dir}/${split.test_dir}
        --param-path params.yaml
        --param-parent-key classifier
        --out-model-path ${item.out_model_path}
        --out-label-encoder-path ${item.out_label_encoder}
        --out-metrics-path ${item.out_metrics_path}
        --use-imagenet ${item.use_imagenet}
        --is-frozen ${item.is_frozen}
      params:
        - classifier
      deps:
        - ${classifier_src}
        - ${siamese_types.distance.out_encoder_path}
        - ${out_dir}/${split.train_dir}
        - ${out_dir}/${split.test_dir}
      outs:
        - ${item.out_model_path}
        - ${item.out_label_encoder}
      # TODO why no metrics html?
      plots:
        - ${item.out_metrics_path}
      metrics:
        - ${item.out_metrics_path}.json:
            cache: false
        #- ${item.out_summaries_path}
      #live:
        #${item.out_metrics_path}:
          #summary: true
          #html: true

  # TODO continue hydra experiments
  #hydra:
    #cmd: >
      #${docker_cmd} ${train.docker_args} 
      #${train.img} hydra.py
    #params:
      #- train.img
      #- train.docker_args
    #deps:
      #- last_build.log
      