#out_dir: /nfs/data/gloves
#- docker_cmd: docker run -v $(pwd)/outputs:/outputs
# TODO fix this absolute path
#out_dir: /nfs/data/gloves/outputs
out_dir: artifacts
docker_out_dir: /gloves/artifacts
#docker_cmd: docker run -v /nfs/data/gloves/outputs:/outputs
docker_cmd: docker run -v ${PWD}:/gloves --user 1000:1000

wget:
  img: etheredgeb/wget_url:latest
  data_url: https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz
  out_dir: wget

untar:
  img: etheredgeb/untar_data:latest
  tar_args: xzvf
  data_dir: untar
  tar_file_name: images.tar.gz

clean:
  img: etheredgeb/clean_oxford_pet_data:latest
  out_dir: clean

split:
  img: etheredgeb/split_oxford_pet_data:latest
  train_dir: train
  test_dir: test
  ratio: 0.1


siamese:

  src: gloves/main.py

  types:
    distance:
      out_model_path: artifacts/models/siamese_distance/model
      out_encoder_path: artifacts/models/siamese_distance/encoder
      out_metrics_path: logs/distance_siamese_logs
      sigmoid_head: False
    sigmoid:
      out_model_path: artifacts/models/siamese_sigmoid/model
      out_encoder_path: artifacts/models/siamese_sigmoid/encoder
      out_metrics_path: logs/sigmoid_siamese_logs
      sigmoid_head: True

  # Image
  height: 224
  width: 224
  depth: 3
  # hypers
  mutate_anchor: true
  mutate_other: true
  dense_layers: 0
  dense_nodes: 1024
  dense_reg_rate: 0.001
  conv_reg_rate: 0.0001
  activation: sigmoid
  latent_nodes: 32
  dropout_rate: 0.0
  final_activation: sigmoid
  lr: 0.0001
  optimizer: adam
  epochs: 1
  batch_size: 32
  verbose: 0
  eval_freq: 1
  reduce_lr_factor: 0.1
  reduce_lr_patience: 20
  early_stop_patience: 50
  mixed_precision: true
  nway_freq: 20
  nways: 32
  use_batch_norm: true


classifier:
  src: gloves/classifier.py
  types:
    imagenet_frozen:
      out_model_path: artifacts/models/imagenet_frozen
      out_label_encoder: artifacts/models/imagenet_frozen_label_encoder.joblib
      out_metrics_path: logs/imagenet_frozen
      use_imagenet: true
      is_frozen: true
    imagenet_unfrozen:
      out_model_path: artifacts/models/imagenet_unfrozen
      out_label_encoder: artifacts/models/imagenet_unfrozen_label_encoder.joblib
      out_metrics_path: logs/imagenet_unfrozen
      use_imagenet: true
      is_frozen: false
    gloves_frozen:
      out_model_path: artifacts/models/gloves_frozen
      out_label_encoder: artifacts/models/gloves_frozen_label_encoder.joblib
      out_metrics_path: logs/gloves_frozen
      use_imagenet: false
      is_frozen: true
    gloves_unfrozen:
      out_model_path: artifacts/models/gloves_unfrozen
      out_label_encoder: artifacts/models/gloves_unfrozen_label_encoder.joblib
      out_metrics_path: logs/gloves_unfrozen
      use_imagenet: false
      is_frozen: false
  # hypers
  batch_size: 32
  epochs: 1
  verbose: 1
