#out_dir: /nfs/data/gloves
#- docker_cmd: docker run -v $(pwd)/outputs:/outputs
# TODO fix this absolute path
#out_dir: /nfs/data/gloves/outputs
out_dir: artifacts
docker_out_dir: /app/gloves/artifacts
docker_work_dir: /app/gloves
#docker_cmd: docker run -v /nfs/data/gloves/outputs:/outputs
docker_cmd: docker run -v ${PWD}:/app/gloves --user 1000:1000
mlflow_env_vars: '
      -e MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI} 
      -e MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME} 
      -e MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      -e MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      '
wandb_env_vars: -e WANDB_API_KEY=${WANDB_API_KEY}
gloves_train_image: etheredgeb/gloves:custom-tensorflow-2.7.0

wget:
  img: etheredgeb/wget_url:latest
  data_url: https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz
  out_dir: wget

untar:
  img: etheredgeb/untar_data:latest
  tar_args: xzvf
  data_dir: untar
  tar_file_name: images.tar.gz

clean:
  img: etheredgeb/clean_oxford_pet_data:latest
  out_dir: clean

split:
  img: etheredgeb/split_oxford_pet_data:latest
  train_dir: train
  test_dir: test
  ratio: 0.1

siamese_types:
  distance:
    out_model_path: artifacts/models/siamese_distance/model
    out_encoder_path: artifacts/models/siamese_distance/encoder
    out_metrics_path: logs/distance_siamese_logs
    out_summaries_path: logs/distance_siamese_summaries
    sigmoid_head: false
  sigmoid:
    out_model_path: artifacts/models/siamese_sigmoid/model
    out_encoder_path: artifacts/models/siamese_sigmoid/encoder
    out_metrics_path: logs/sigmoid_siamese_logs
    out_summaries_path: logs/sigmoid_siamese_summaries
    sigmoid_head: true

siamese_src: gloves/main.py
siamese_model_src: gloves/models/custom_model.py

siamese:
  # Image
  height: 224
  width: 224
  depth: 3
  # hypers
  mutate_anchor: true
  mutate_other: true
  dense_layers: 0
  dense_nodes: 1024
  dense_reg_rate: 0.001
  conv_reg_rate: 0.0001
  activation: sigmoid
  latent_nodes: 32
  dropout_rate: 0.0
  final_activation: linear
  lr: 0.0001
  optimizer: adam
  epochs: 200
  batch_size: 32
  verbose: 0
  eval_freq: 1
  reduce_lr_factor: 0.1
  reduce_lr_patience: 20
  early_stop_patience: 50
  mixed_precision: true
  nway_freq: 20
  nways: 32
  use_batch_norm: true

classifier_src: gloves/classifier.py

classifier_types:
  imagenet_frozen:
    out_model_path: artifacts/models/gloves_imagenet_frozen
    out_label_encoder: artifacts/models/gloves_imagenet_frozen_label_encoder.joblib
    out_metrics_path: logs/imagenet_frozen
    out_summaries_path: logs/imagenet_frozen_summaries
    use_imagenet: true
    is_frozen: true
  imagenet_unfrozen:
    out_model_path: artifacts/models/gloves_imagenet_unfrozen
    out_label_encoder: artifacts/models/gloves_imagenet_unfrozen_label_encoder.joblib
    out_metrics_path: logs/imagenet_unfrozen
    out_summaries_path: logs/imagenet_unfrozen_summaries
    use_imagenet: true
    is_frozen: false
  gloves_frozen:
    out_model_path: artifacts/models/gloves_encoder_frozen
    out_label_encoder: artifacts/models/gloves_encoder_frozen_label_encoder.joblib
    out_metrics_path: logs/gloves_frozen
    out_summaries_path: logs/gloves_frozen_summaries
    use_imagenet: false
    is_frozen: true
  gloves_unfrozen:
    out_model_path: artifacts/models/gloves_encoder_unfrozen
    out_label_encoder: artifacts/models/gloves_encoder_unfrozen_label_encoder.joblib
    out_metrics_path: logs/gloves_unfrozen
    out_summaries_path: logs/gloves_unfrozen_summaries
    use_imagenet: false
    is_frozen: false

classifier:
  # hypers
  batch_size: 32
  epochs: 200
  verbose: 1
