program: gloves/train_siamese.py
method: bayes
metric:
  goal: maximize
  name: test_nway_acc
early_terminate:
  type: hyperband
  min_iter: 200
  s: 4

parameters:
  train_dir: 
    value: artifacts/train
  test_dir: 
    value: artifacts/test

  conv_layers:
    min: 1
    max: 6
  pooling:
    values:
      - avg
      - max
      - None
  latent_dense:
    values:
      - True
      - False
  mutate_anchor:
    values:
      - True
      - False
  mutate_other:
    values:
      - True
      - False
  dense_reg_rate:
    values:
      - 0.01
      - 0.001
      - 0.0001
      - 0.0
    #distribution: log_uniform
  conv_reg_rate:
    values:
      - 0.001
      - 0.0001
      - 0.00001
      - 0.0
    # min: 0.0
    # max: 0.1
    #distribution: log_uniform
  latent_nodes:
    values:
      - 1
      - 2
      - 4
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
    # distribution: q_log_uniform
    # q: 2

  final_activation:
    values:
      - linear
      - sigmoid
      #- softmax
      # - relu

  lr:
    values:
      - 0.01
      - 0.001
      - 0.0001
      - 0.00001
      - 0.000001
    # min: 0.000001
    # max: 0.01
    #distribution: log_uniform
  optimizer:
    values:
      - adam
      - sgd
      - rmsprop
      # - adagrad
      # - adadelta
      # - adamax
  epochs: 
    value: 1000

  nways: 
    value: 16
  batch_size: 
    value: 16 # locking in for now due to batch norm and nway
    # values:
    #   - 1
    #   - 4
    #   - 16
    #   - 32
    #   - 64
  reduce_lr_factor:
    values: 
      - 0.1
      - 0.5
      - 0.9
    #distribution: log_uniform
  reduce_lr_patience:
    values:
      - 5
      - 10
      - 20
      - 50
  use_batch_norm:
    values:
      - True
      - False
  distance:
    values:
      #- None
      - l1
      - l2
      - cosine
      - sigmoid
  use_sigmoid:
    value: False
    # values:
    #   - True
    #   - False

  monitor_metric:
    values:
      - loss
      - val_loss
      #- acc
      #- val_acc
      #- test_nway_acc
      #- train_nway_acc

