# NOTE: Will run on all branches, so different branches can override main image
#       could maybe be fixed with logic to only run on master branch 
#       or to add a tag for branch and/or no tag for main branch
name: Build Docker Images for Training
on:
  push:
    paths:
      - '.github/workflows/build_image.yaml'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push CI/CD Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: etheredgeb/gloves:custom-tensorflow-2.7.0